{{- if .Values.web.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mantis.web.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mantis.web.labels" . | nindent 4 }}
  {{- with .Values.web.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.web.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.web.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.web.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "mantis.web.fullname" $ }}
                port:
                  number: {{ $.Values.web.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
